# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClientApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'Alamofire', '~>4.0.1'
   pod 'SwiftyJSON', '~>3.1'
   pod 'ProgressHUD', '~>2.3'
  # Pods for ClientApp

  target 'ClientAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClientAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
